"""Add tags to Destination model

Revision ID: 1c08a23546eb
Revises: fdb67e184994
Create Date: 2025-07-01 10:05:03.135202

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c08a23546eb'
down_revision: str | Sequence[str] | None = 'fdb67e184994'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'tags')
    # ### end Alembic commands ###
