"""update weather_data model with detailed fields

Revision ID: 4438c2490416
Revises: f876c34140e8
Create Date: 2025-06-30 18:25:42.830117

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4438c2490416'
down_revision: str | Sequence[str] | None = 'f876c34140e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('grid_x', sa.Integer(), nullable=True))
    op.add_column('weather_data', sa.Column('grid_y', sa.Integer(), nullable=True))
    op.add_column('weather_data', sa.Column('forecast_time', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('base_date', sa.Date(), nullable=True))
    op.add_column('weather_data', sa.Column('base_time', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('weather_data', sa.Column('precipitation_probability', sa.Float(), nullable=True))
    op.add_column('weather_data', sa.Column('precipitation_type', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('sky_condition', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('region_name', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('weather_data', 'destination_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_data', 'destination_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('weather_data', 'raw_data')
    op.drop_column('weather_data', 'region_name')
    op.drop_column('weather_data', 'sky_condition')
    op.drop_column('weather_data', 'precipitation_type')
    op.drop_column('weather_data', 'precipitation_probability')
    op.drop_column('weather_data', 'temperature')
    op.drop_column('weather_data', 'base_time')
    op.drop_column('weather_data', 'base_date')
    op.drop_column('weather_data', 'forecast_time')
    op.drop_column('weather_data', 'grid_y')
    op.drop_column('weather_data', 'grid_x')
    # ### end Alembic commands ###
