"""updates to travel_plans

Revision ID: 64996c3abf5b
Revises: 72710c00e558
Create Date: 2025-07-05 21:01:39.655826

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64996c3abf5b'
down_revision: str | Sequence[str] | None = '72710c00e558'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### end Alembic commands ###
    status_enum = sa.Enum('PLANNING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='travelplanstatus')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('travel_plans', sa.Column('status', status_enum, nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_plans', 'status')
    status_enum = sa.Enum('PLANNING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='travelplanstatus')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
