"""Initial migration

Revision ID: 64b40983a634
Revises: 
Create Date: 2025-06-25 16:45:46.137146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64b40983a634'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_kma_regions_reg_id'), table_name='kma_regions')
    op.drop_index(op.f('idx_kma_regions_reg_name'), table_name='kma_regions')
    op.drop_index(op.f('idx_kma_regions_reg_sp'), table_name='kma_regions')
    op.drop_index(op.f('idx_kma_regions_tm_ed'), table_name='kma_regions')
    op.drop_index(op.f('idx_kma_regions_tm_st'), table_name='kma_regions')
    op.drop_table('kma_regions')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('kma_regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='자동 증가 기본키'),
    sa.Column('reg_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='지역구분코드 (예: 11A00101)'),
    sa.Column('tm_st', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='시작시간 (YYYYMMDDHHMI, KST)'),
    sa.Column('tm_ed', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='종료시간 (YYYYMMDDHHMI, KST)'),
    sa.Column('reg_sp', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='특성 (A:전국, B:지방, C:시군구, D:해상, E:해상도로, H:제주도, I:제주시, J:서귀포시, K:제주시군구, L:서귀포시군구, M:시군구, P:해상, P7:해상(서해중부), P8:해상(동해중부), P9:해상(서해남부))'),
    sa.Column('reg_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='지역구분명 (예: 서울, 부산, 제주)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='생성일시'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id', name=op.f('kma_regions_pkey')),
    sa.UniqueConstraint('reg_id', name=op.f('uk_kma_regions_reg_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='기상청(KMA) 지역 코드 정보'
    )
    op.create_index(op.f('idx_kma_regions_tm_st'), 'kma_regions', ['tm_st'], unique=False)
    op.create_index(op.f('idx_kma_regions_tm_ed'), 'kma_regions', ['tm_ed'], unique=False)
    op.create_index(op.f('idx_kma_regions_reg_sp'), 'kma_regions', ['reg_sp'], unique=False)
    op.create_index(op.f('idx_kma_regions_reg_name'), 'kma_regions', ['reg_name'], unique=False)
    op.create_index(op.f('idx_kma_regions_reg_id'), 'kma_regions', ['reg_id'], unique=False)
    # ### end Alembic commands ###