"""add start_location to travel_plans

Revision ID: 9028709b2871
Revises: 64996c3abf5b
Create Date: 2025-07-06 00:30:22.484252

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9028709b2871'
down_revision: str | Sequence[str] | None = '64996c3abf5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plans', sa.Column('start_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_plans', 'start_location')
    # ### end Alembic commands ###
