"""Add password_hash to contact

Revision ID: 90f6e197695f
Revises: 0fd45bc85fb9
Create Date: 2025-07-15 15:33:57.029550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f6e197695f'
down_revision: Union[str, Sequence[str], None] = '0fd45bc85fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'password_hash')
    # ### end Alembic commands ###
