"""update user model

Revision ID: a29d1bc1f1d0
Revises: 64b40983a634
Create Date: 2025-06-25 16:48:07.579816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29d1bc1f1d0'
down_revision = '64b40983a634'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###