"""Add weather_info field to TravelPlan model

Revision ID: c81ebbb9afa1
Revises: 9028709b2871
Create Date: 2025-07-07 12:00:03.809133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81ebbb9afa1'
down_revision: Union[str, Sequence[str], None] = '9028709b2871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plans', sa.Column('weather_info', postgresql.JSONB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_plans', 'weather_info')
    # ### end Alembic commands ###